export default [
  'Model S',
  'Model 3',
  'Model X',
  'Model Y',
  'Solar Roof',
  'Solar Panels',
  'Existing Inventor',
  'Used Inventory',
  'Trade-In',
  'Test Drive',
  'Powerwall',
  'Commercial Energy',
  'Utilities',
  'Charging',
  'Find Us',
  'Support',
  'Investor Relations',
  'Shop',
  'Account',
];
